const FIFTEEN = 15;
const TWENTYFOUR = 24;
const FIFTEEN_WORDS_BIT_LENGTH = 160;
const TWENTYFOUR_WORDS_BIT_LENGTH = 256;

export {
  FIFTEEN,
  FIFTEEN_WORDS_BIT_LENGTH,
  TWENTYFOUR,
  TWENTYFOUR_WORDS_BIT_LENGTH,
};
