const MNEMONIC_FIFTEEN_WORDS = 15;
const MNEMONIC_TWENTYFOUR_WORDS = 24;
const FIFTEEN_WORDS_BIT_LENGTH = 160;
const TWENTYFOUR_WORDS_BIT_LENGTH = 256;
const DISPLAY_NAME_LENGTH = 32;
const SEED_PHRASE_SUGGESTIONS = 3;

export {
  MNEMONIC_FIFTEEN_WORDS,
  MNEMONIC_TWENTYFOUR_WORDS,
  FIFTEEN_WORDS_BIT_LENGTH,
  TWENTYFOUR_WORDS_BIT_LENGTH,
  DISPLAY_NAME_LENGTH,
  SEED_PHRASE_SUGGESTIONS,
};
