# syntax=docker/dockerfile:1.3-labs
FROM node:22

ARG SIGNIFY_GIT_REPOSITORY=https://github.com/WebOfTrust/signify-ts
ARG SIGNIFY_GIT_BRANCH=main

RUN git clone --branch $SIGNIFY_GIT_BRANCH $SIGNIFY_GIT_REPOSITORY /app
WORKDIR /app
RUN npm install
RUN npm run build

COPY <<EOF passcode-gen.js
import { randomPasscode, ready } from \'signify-ts\';
await ready();
const bran = randomPasscode();
console.log(bran);
EOF

CMD node passcode-gen.js
