const DISPLAY_NAME_LENGTH = 32;
const SEED_PHRASE_SUGGESTIONS = 3;
const MAX_FAVOURITES = 5;
const DOUBLE_TAP_DELAY = 300;

const DISCORD_LINK = process.env.REACT_APP_DISCORD_LINK || "";
const DOCUMENTATION_LINK = process.env.REACT_DOCUMENTATION_LINK || "";

export {
  DISPLAY_NAME_LENGTH,
  SEED_PHRASE_SUGGESTIONS,
  MAX_FAVOURITES,
  DOUBLE_TAP_DELAY,
  DISCORD_LINK,
  DOCUMENTATION_LINK,
};
