keri:
  keria:
    url: "http://127.0.0.1:3901"
    bootUrl: "http://127.0.0.1:3903"
  credentials:
    testServer:
      urlExt: "http://127.0.0.1:3001"
      urlInt: "http://cred-issuance:3001"
      oobiUrl: "http://keria:3902/oobi"
  backing:
    mode: direct 
