keri:
  credentials:
    testServer:
      urlInt: "https://cred-issuance.dev.cf-summit-2024.eu-west-1.metadata.dev.cf-deployments.org"
  backing:
    mode: ledger
    ledger:
      aid: BD39IWoiPYhhq5yn2l7FTQykcjhZma1KmfWrWr9ZYUFD
      address: addr_test1vqefk7cyhcyet03humlzkyl2cj8jwezvr6gu8cg8jrkdq7cf30wpu
