# Workflow to build and verify branch
# Name of Workflow
name: verify-branch

# Controls when the action will run. Triggers the workflow on push
# events but only for specified branches
on:
  push:
    branches:
      - main

env:
  PRODUCTION_BRANCH: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-branch:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Fetch private content
        fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Audit Dependencies
      run: |
        npm ci
        npm run audit
    
    - name: Run unit tests
      env:
        NODE_OPTIONS: "--max_old_space_size=8192"
      run: npm run test

    - name: 🔨 Build project
      run: npm run build
