# deploy-preview.yaml

# Workflow to build and verify pr
# Name of Workflow
name: verify-pr

# Controls when the action will run. Triggers the workflow on push
# events but only for the develop branch
on:
  pull_request:
    types: [ opened, synchronize ]
    branches-ignore: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-preview"
  deploy-preview:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Make some more metadata available as variables
      id: metadata
      run: |
        if [ ${{github.event_name }} == "pull_request" ]
        then
          echo "::set-output name=DEPLOY_NAME::PR-$(echo $GITHUB_REF | awk -F/ '{ print $3 }')"
        else
          echo "::set-output name=DEPLOY_NAME::BRANCH-${GITHUB_REF##*/}"
        fi

    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive  # Fetch private content
          fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Run unit tests
      env:
        NODE_OPTIONS: "--max_old_space_size=8192"
      run: |
        npm ci
        npm run test

    - name: Audit Dependencies
      run: |
        npm audit --json > scripts/audit-results.json
        cat scripts/audit-results.json
        node scripts/audit-filter.js

    - name: 🔨 Build project
      run: npm run build